util.py::read_possibly_signed: fix issue with python3 by using subp
$ ./tools/tenv python3 bin/sstream-query \
    exdata/data/released/streams/v1/index.sjson
Traceback (most recent call last):
  File "bin/sstream-query", line 140, in <module>
    main()
  File "bin/sstream-query", line 137, in main
    tmirror.sync(smirror.reader, path)
  File "trunk/simplestreams/mirrors/__init__.py", line 54, in sync
    (payload, _sig) = util.read_possibly_signed(path, reader)
  File "trunk/simplestreams/util.py", line 230, in read_possibly_signed
    (out, _err) = sp.communicate(content)
  ....
TypeError: 'str' does not support the buffer interface

It worked with python2, but not python3.

bzr-revno: 272